apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: db-pv-claim #during pod creation we tell to mount this volume to /var/lib/msql
    labels:
        app: vprodb
spec:
    storageClassName: default
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 3Gi
